export const COLORS = {
  WORKFLOW_NODE: "#778beb",
  WORKFLOW_APPROVED_NODE: "#64cddb",
  WORKFLOW_CONDITION_NODE: "#f9b679",
  WORKFLOW_TREE_LINE_COLOR: "#2563eb",
  FORM_UPDATE_BUTTON: "#DBAE58",
  PRIMARY: "#213389",
};
